# ==============================================================================
# File: Dockerfile
# Description: This Dockerfile to create a CPU based lean and efficient Docker
#              image for the MISRA Smart Fixer application.
#
# Author: Dipesh Karmakar
#
# This source code is licensed under the MIT License. See the LICENSE file in the
# project root for the full license text.
#
# Version: 1.0
# ==============================================================================

# Stage 1: The builder stage to compile llama-cpp-python with CUDA support
FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip ninja-build && \
    apt-get install -y cppcheck && \
    rm -rf /var/lib/apt/lists/*

ENV PIP_BREAK_SYSTEM_PACKAGES=1

# Copy the requirements file into the container at /app
COPY requirements_CPU.txt .

# Install the dependencies, including llama-cpp-python
RUN pip install --no-cache-dir -r requirements_CPU.txt

# A build argument needs to be passed the model file to the Docker build command.
# We also provide a default value to prevent build failures if the argument is not passed.
ARG MODEL_FILE=codellama-7b-instruct.Q4_K_M.gguf

# Copy the application files and the large model file
COPY app_CPU.py .
COPY ${MODEL_FILE} /app/Model.gguf

# Expose the application port
EXPOSE 7860

ENV PYTHONUNBUFFERED=1

# Define the command to run the application
CMD ["python3", "app_CPU.py"]
